name: Helmfile
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    name: "TEST"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helmfile-version: v0.155.1
          helm-version: v3.12.0

      - name: Run helmfile
        continue-on-error: true
        run: |
          helmfile apply --environment staging --file ./environments/staging

      - name: Get POD
        run: |
          kubectl get po -n staging
